In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import warnings
warnings.simplefilter("ignore")

In [6]:
us=pd.read_csv('Old_USvideos.csv',error_bad_lines=False)
us.head()

b'Skipping line 2401: expected 11 fields, saw 21\nSkipping line 2800: expected 11 fields, saw 21\nSkipping line 5297: expected 11 fields, saw 12\nSkipping line 5299: expected 11 fields, saw 12\nSkipping line 5300: expected 11 fields, saw 12\nSkipping line 5301: expected 11 fields, saw 12\n'


video_id                                              title  \
0  XpVt6Z1Gjjo  1 YEAR OF VLOGGING -- HOW LOGAN PAUL CHANGED Y...   
1  K4wEI5zhHB0            iPhone X — Introducing iPhone X — Apple   
2  cLdxuaxaQwc                                        My Response   
3  WYYvHb03Eog                          Apple iPhone X first look   
4  sjlHnJvXdQs                                  iPhone X (parody)   

      channel_title  category_id  \
0  Logan Paul Vlogs           24   
1             Apple           28   
2         PewDiePie           22   
3         The Verge           28   
4        jacksfilms           23   

                                                tags    views   likes  \
0  logan paul vlog|logan paul|logan|paul|olympics...  4394029  320053   
1  Apple|iPhone 10|iPhone Ten|iPhone|Portrait Lig...  7860119  185853   
2                                             [none]  5845909  576597   
3  apple iphone x hands on|Apple iPhone X|iPhone ...  2642103   24975   
4  jacksfilms|parody|parodies|iphone|iphone x|iph...  1168130   96666   

   dislikes  comment_total                                  thumbnail_link  \
0      5931          46245  https://i.ytimg.com/vi/XpVt6Z1Gjjo/default.jpg   
1     26679              0  https://i.ytimg.com/vi/K4wEI5zhHB0/default.jpg   
2     39774         170708  https://i.ytimg.com/vi/cLdxuaxaQwc/default.jpg   
3      4542          12829  https://i.ytimg.com/vi/WYYvHb03Eog/default.jpg   
4       568           6666  https://i.ytimg.com/vi/sjlHnJvXdQs/default.jpg   

    date  
0  13.09  
1  13.09  
2  13.09  
3  13.09  
4  13.09

In [7]:
us.sort_values('date', ascending=False, inplace=True)

In [8]:
us.drop_duplicates('video_id', keep = 'first', inplace = True)

In [9]:
us.shape

(2364, 11)

In [10]:
category =pd.read_json('US_category_id.json')
id_video =[]
video_name = []
for index,row in category.iterrows():
    x = row['items']
    id_video.append(x['id'])
    video_name.append(x['snippet']['title'])

category = pd.DataFrame(zip(id_video, video_name),columns=['category_id', 'category'])
category['category_id'] = category['category_id'].astype('int64')

#Instead of maintaining two different datasets, I merged both into one by adding categories into the original 'data' dataset.
us_cate = pd.merge(us, category, on = 'category_id', how = 'inner')
us_cate.head()

video_id                                              title  \
0  tqUKbEfW-B8     IGN Live: Red Dead Redemption 2 Trailer Reveal   
1  SNGWh_-R1VE                    This is Star Wars Battlefront 2   
2  Y12lF3cYufo            Clash of Clans - Builder Hall 7 UPDATE!   
3  lw-Xu7ZLD3w  Clash of Clans: Builder Hall 7 Update Coming S...   
4  A9U5wK_boYM  How I Fixed a 10 Year Old Guitar Hero Bug With...   

    channel_title  category_id  \
0             IGN           20   
1    EA Star Wars           20   
2  Clash of Clans           20   
3  Clash of Clans           20   
4       ExileLord           20   

                                                tags    views   likes  \
0  ign|Feature|PS4|Red Dead Redemption 2|games|Ac...   302270    6164   
1  this is star wars|this is battlefront|this is ...  3384577  121972   
2  clash of clans|COC|Clash of Clans Gameplay|Cla...  1847810   45150   
3  clash of clans|COC|Clash of Clans Gameplay|Cla...  2785219   52036   
4  Guitar Hero III: Legends of Rock|Guitar Hero|H...    87076    3518   

   dislikes  comment_total                                  thumbnail_link  \
0       669            609  https://i.ytimg.com/vi/tqUKbEfW-B8/default.jpg   
1      3291          23436  https://i.ytimg.com/vi/SNGWh_-R1VE/default.jpg   
2      2633           2038  https://i.ytimg.com/vi/Y12lF3cYufo/default.jpg   
3      2316           5828  https://i.ytimg.com/vi/lw-Xu7ZLD3w/default.jpg   
4        21            227  https://i.ytimg.com/vi/A9U5wK_boYM/default.jpg   

    date category  
0  30.09   Gaming  
1  30.09   Gaming  
2  30.09   Gaming  
3  29.09   Gaming  
4  28.09   Gaming

In [11]:
us_cate['category'].unique()

array(['Gaming', 'Howto & Style', 'Music', 'Entertainment',
       'News & Politics', 'Sports', 'Education', 'Comedy',
       'Film & Animation', 'People & Blogs', 'Pets & Animals',
       'Science & Technology', 'Autos & Vehicles', 'Travel & Events',
       'Nonprofits & Activism', 'Shows'], dtype=object)

In [12]:
comments=pd.read_csv('UScomments.csv',usecols=['video_id','comment_text'],error_bad_lines=False)
final_df = pd.merge(us_cate, comments, on = 'video_id', how = 'left')
final_df.head()

video_id                                           title channel_title  \
0  tqUKbEfW-B8  IGN Live: Red Dead Redemption 2 Trailer Reveal           IGN   
1  tqUKbEfW-B8  IGN Live: Red Dead Redemption 2 Trailer Reveal           IGN   
2  tqUKbEfW-B8  IGN Live: Red Dead Redemption 2 Trailer Reveal           IGN   
3  tqUKbEfW-B8  IGN Live: Red Dead Redemption 2 Trailer Reveal           IGN   
4  tqUKbEfW-B8  IGN Live: Red Dead Redemption 2 Trailer Reveal           IGN   

   category_id                                               tags   views  \
0           20  ign|Feature|PS4|Red Dead Redemption 2|games|Ac...  302270   
1           20  ign|Feature|PS4|Red Dead Redemption 2|games|Ac...  302270   
2           20  ign|Feature|PS4|Red Dead Redemption 2|games|Ac...  302270   
3           20  ign|Feature|PS4|Red Dead Redemption 2|games|Ac...  302270   
4           20  ign|Feature|PS4|Red Dead Redemption 2|games|Ac...  302270   

   likes  dislikes  comment_total  \
0   6164       669            609   
1   6164       669            609   
2   6164       669            609   
3   6164       669            609   
4   6164       669            609   

                                   thumbnail_link   date category  \
0  https://i.ytimg.com/vi/tqUKbEfW-B8/default.jpg  30.09   Gaming   
1  https://i.ytimg.com/vi/tqUKbEfW-B8/default.jpg  30.09   Gaming   
2  https://i.ytimg.com/vi/tqUKbEfW-B8/default.jpg  30.09   Gaming   
3  https://i.ytimg.com/vi/tqUKbEfW-B8/default.jpg  30.09   Gaming   
4  https://i.ytimg.com/vi/tqUKbEfW-B8/default.jpg  30.09   Gaming   

                                        comment_text  
0  It's a prequel guys they had Dutch in the trailer  
1  Van der Linde was a side character that wasn't...  
2  Two people who seem haven't a clue about rdr1 ...  
3   When is bully 2 coming i am excited about that ☺  
4                    magnificent 7 was a great movie

In [14]:
#Music, Entertainment, Comedy, People & Blogs, Film & Animation
final_df=final_df.loc[(final_df['category']=='Music')|(final_df['category']=='Comedy') | (final_df['category']=='People & Blogs') | (final_df['category']=='Entertainment')| (final_df['category']=='Film & Animation')]
final_df['category'].unique()

array(['Music', 'Entertainment', 'Comedy', 'Film & Animation',
       'People & Blogs'], dtype=object)

In [15]:
final_df=final_df.sample(5000)

In [16]:
final_df.shape

(5000, 13)

In [17]:
len(final_df['video_id'].unique())

1148

In [18]:
final_df.describe()

category_id         views         likes       dislikes  comment_total  \
count  5000.000000  5.000000e+03  5.000000e+03    5000.000000    5000.000000   
mean     18.126200  1.513240e+06  5.657297e+04    3018.883400    7318.931000   
std       7.477905  3.274014e+06  1.343505e+05   16443.379315   35460.860698   
min       1.000000  0.000000e+00  0.000000e+00       0.000000       3.000000   
25%      10.000000  1.888678e+05  5.103000e+03     148.000000     577.500000   
50%      22.000000  6.029980e+05  1.548600e+04     517.000000    1632.000000   
75%      24.000000  1.670947e+06  5.479500e+04    1710.000000    4738.000000   
max      24.000000  4.150067e+07  2.010366e+06  318404.000000  736179.000000   

              date  
count  5000.000000  
mean     18.976920  
std       7.289239  
min       1.100000  
25%      14.090000  
50%      19.100000  
75%      24.090000  
max      30.090000

In [19]:
final_df['channel_title'].value_counts()[:20].sort_values(ascending=False)

jacksfilms                                50
The Late Late Show with James Corden      48
Netflix                                   48
TheEllenShow                              47
Safiya Nygaard                            45
CollegeHumor                              45
vlogbrothers                              44
Simply Nailogical                         42
Good Mythical Morning                     40
Meet Arnold                               38
Jimmy Kimmel Live                         36
BuzzFeedVideo                             35
SuperCarlinBrothers                       34
iJustine                                  34
The Tonight Show Starring Jimmy Fallon    33
The Late Show with Stephen Colbert        32
Team Coco                                 32
Grace Helbig                              32
Wil Dasovich                              32
Liza Koshy                                31
Name: channel_title, dtype: int64

# Sentiment Analysis

In [20]:
import re
import string
from nltk.stem import PorterStemmer
porter = PorterStemmer()

# predict category

In [21]:
# Missing Values
num_missing_desc = final_df.isnull().sum()[2]    # No. of values with msising descriptions
print('Number of missing values: ' + str(num_missing_desc))
final_df = final_df.dropna()

Number of missing values: 0


In [22]:
from nltk.tokenize import word_tokenize

In [23]:
final_df['tags'] = final_df['tags'].map(lambda x:' '.join((x.split('|'))))

In [24]:
final_df['tags'] = final_df['tags'].map(lambda x: x.lower())
final_df['tags'] = final_df['tags'].map(lambda x: re.sub(r'\d+', '', x))
final_df['tags'] = final_df['tags'].map(lambda x: x.translate(x.maketrans('', '', string.punctuation)))
final_df['tags'] = final_df['tags'].map(lambda x: x.strip())

In [25]:
final_df['title'] = final_df['title'].map(lambda x: x.lower())
final_df['title'] = final_df['title'].map(lambda x: re.sub(r'\d+', '', x))
final_df['title'] = final_df['title'].map(lambda x: x.translate(x.maketrans('', '', string.punctuation)))
final_df['title'] = final_df['title'].map(lambda x: x.strip())

In [26]:
final_df['tags'] = final_df['tags'].map(lambda x: word_tokenize(x))
final_df['title'] = final_df['title'].map(lambda x: word_tokenize(x))

In [27]:
final_df['tags']= final_df['tags'].map(lambda x: [word for word in x if word.isalpha()])
final_df['title']= final_df['title'].map(lambda x: [word for word in x if word.isalpha()])

In [28]:
from nltk.corpus import stopwords
stop = stopwords.words('english')

In [29]:
final_df['tags'] = final_df['tags'].map(lambda x: [w for w in x if not w in stop])
final_df['title'] = final_df['title'].map(lambda x: [w for w in x if not w in stop])

In [30]:
from nltk.stem import WordNetLemmatizer
wnl = WordNetLemmatizer()

In [31]:
final_df['tags'] = final_df['tags'].map(lambda x: [wnl.lemmatize(word,"v") for word in x])
final_df['title'] = final_df['title'].map(lambda x: [wnl.lemmatize(word,"v") for word in x])

In [32]:
final_df['tags'] = final_df['tags'].map(lambda x: ' '.join(x))
final_df['title'] = final_df['title'].map(lambda x: ' '.join(x))

# Label Encoding classes


In [33]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(final_df.category)
final_df.category = le.transform(final_df.category)
final_df

video_id                                              title  \
331127  Ga1uiDaqMjQ                          boy honk swallow toy horn   
303592  a5F05Qpi6lM                meghan mccain join view cohost view   
281576  Zya-JNMJ62k                                           hell yes   
298944  RaKxVWJxA2U  star war last jedi trailer breakdown nerdist n...   
119078  XF_ARz7jTUw                          look make taylor mountain   
...             ...                                                ...   
506262  z5Wo-iF6lA8                   allergic cyanide happiness short   
296176  WSFJsq_jwMs   bruno mar thats like acoustic remix charlie rise   
153795  fS5xHHqW-6E                                x ambassadors ahead   
297846  1ZNZY-gd3K0       joe arpaio last week tonight john oliver hbo   
164686  JhA1Wi9mrns              kid rock tennessee mountain top lyric   

                     channel_title  category_id  \
331127  Storyful Rights Management           24   
303592                    The View           24   
281576                  Jack Black           24   
298944                     Nerdist           24   
119078                Taylor Swift           10   
...                            ...          ...   
506262        ExplosmEntertainment           23   
296176                Charlie Rose           24   
153795            XAmbassadorsVEVO           10   
297846             LastWeekTonight           24   
164686                    Kid Rock           10   

                                                     tags    views  likes  \
331127                                storyful news viral   364644    772   
303592          meghan mccain john mccain view hot topics   231986   1505   
281576  jack black jables black tenacious king jables ...   445225   7327   
298944  nerdist fvid nerdist news amy vorpahl star war...   100988   3039   
119078  taylor swift lwymmd reputation transformation ...  1785675  50282   
...                                                   ...      ...    ...   
506262  short chshorts ch short c h short cyanide happ...  1568371  58222   
296176                  music thats like album grammy pbs   326208   8287   
153795  ambassadors ahead kidinakornerinterscope recor...   370459  18297   
297846  last week tonight joe arpaio joe arpaio john o...  3794392  70200   
164686  kid rock greatests show earth po dunk tennesse...   324599   6496   

        dislikes  comment_total  \
331127       111            130   
303592      1630           1949   
281576       248            534   
298944       180            581   
119078      1665           2727   
...          ...            ...   
506262      3631           3332   
296176        85            444   
153795       208            604   
297846      4587           9142   
164686       859            635   

                                        thumbnail_link   date  category  \
331127  https://i.ytimg.com/vi/Ga1uiDaqMjQ/default.jpg   6.10         1   
303592  https://i.ytimg.com/vi/a5F05Qpi6lM/default.jpg  14.10         1   
281576  https://i.ytimg.com/vi/Zya-JNMJ62k/default.jpg  19.09         1   
298944  https://i.ytimg.com/vi/RaKxVWJxA2U/default.jpg  15.10         1   
119078  https://i.ytimg.com/vi/XF_ARz7jTUw/default.jpg  26.09         3   
...                                                ...    ...       ...   
506262  https://i.ytimg.com/vi/z5Wo-iF6lA8/default.jpg  11.10         0   
296176  https://i.ytimg.com/vi/WSFJsq_jwMs/default.jpg  16.10         1   
153795  https://i.ytimg.com/vi/fS5xHHqW-6E/default.jpg  19.09         3   
297846  https://i.ytimg.com/vi/1ZNZY-gd3K0/default.jpg  16.09         1   
164686  https://i.ytimg.com/vi/JhA1Wi9mrns/default.jpg  18.09         3   

                                             comment_text  
331127                In latin Argentina, horn honks you.  
303592                       She sounds like Demi Lovato.  
281576  Looking like a young jack Nicholson you guys s...  
298944                

# Vectorizing text features using TF-IDF¶


In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_title = TfidfVectorizer(sublinear_tf=True, min_df=5, norm='l2', encoding='latin-1', ngram_range=(1, 2), stop_words='english')
tfidf_tags = TfidfVectorizer(sublinear_tf=True, min_df=5, norm='l2', encoding='latin-1', ngram_range=(1, 2), stop_words='english')
labels = final_df.category
features_title = tfidf_title.fit_transform(final_df.title).toarray()
features_tags = tfidf_tags.fit_transform(final_df.tags).toarray()
print('Title Features Shape: ' + str(features_title.shape))
print('Description Features Shape: ' + str(features_tags.shape))

Title Features Shape: (5000, 3537)
Description Features Shape: (5000, 14300)


In [64]:
features_tags

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [35]:
# Best 5 keywords for each class using Title Feaures
from sklearn.feature_selection import chi2
import numpy as np
N = 5
for current_class in list(le.classes_):
    current_class_id = le.transform([current_class])[0]
    features_chi2 = chi2(features_title, labels == current_class_id)
    indices = np.argsort(features_chi2[0])
    feature_names = np.array(tfidf_title.get_feature_names())[indices]
    unigrams = [v for v in feature_names if len(v.split(' ')) == 1]
    bigrams = [v for v in feature_names if len(v.split(' ')) == 2]
    print("# '{}':".format(current_class))
    print("Most correlated unigrams:")
    print('-' *30)
    print('. {}'.format('\n. '.join(unigrams[-N:])))
    print("Most correlated bigrams:")
    print('-' *30)
    print('. {}'.format('\n. '.join(bigrams[-N:])))
    print("\n")

# 'Comedy':
Most correlated unigrams:
------------------------------
. parody
. lele
. pons
. anwar
. jibawi
Most correlated bigrams:
------------------------------
. conan tbs
. hannah stock
. iphone parody
. lele pons
. anwar jibawi


# 'Entertainment':
Most correlated unigrams:
------------------------------
. trailer
. season
. star
. audio
. superfruit
Most correlated bigrams:
------------------------------
. season official
. official trailer
. official video
. hd netflix
. dance star


# 'Film & Animation':
Most correlated unigrams:
------------------------------
. wrong
. nonwhite
. fox
. rick
. trailers
Most correlated bigrams:
------------------------------
. th century
. paramount picture
. trailer paramount
. film theory
. honest trailers


# 'Music':
Most correlated unigrams:
------------------------------
. music
. lyric
. official
. video
. audio
Most correlated bigrams:
------------------------------
. official music
. music video
. lyric video
. official audio
. offici

In [55]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn import linear_model
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn import metrics


In [37]:
X=final_df[['title','tags']]
y=final_df['category']

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 0)
X_train_title_features = tfidf_title.transform(X_train['title']).toarray()
X_train_tags_features = tfidf_tags.transform(X_train['tags']).toarray()
features = np.concatenate([X_train_title_features, X_train_tags_features], axis=1)

In [42]:
X_test_title_features = tfidf_title.transform(X_test['title']).toarray()
X_test_tags_features = tfidf_tags.transform(X_test['tags']).toarray()
test_features = np.concatenate([X_test_title_features, X_test_tags_features], axis=1)

# Naive Bayes Classfication

In [52]:
nb = MultinomialNB().fit(features, y_train)
y_pred = nb.predict(test_features)
y_probas = nb.predict_proba(test_features)

print(confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred, target_names=list(le.classes_)))

[[196   4   2   2   3]
 [  2 395   0   5   2]
 [  1   9  75   4   0]
 [  0   6   0 333   0]
 [  2  15   0   1 193]]
                  precision    recall  f1-score   support

          Comedy       0.98      0.95      0.96       207
   Entertainment       0.92      0.98      0.95       404
Film & Animation       0.97      0.84      0.90        89
           Music       0.97      0.98      0.97       339
  People & Blogs       0.97      0.91      0.94       211

        accuracy                           0.95      1250
       macro avg       0.96      0.93      0.95      1250
    weighted avg       0.95      0.95      0.95      1250



# SVM 

In [59]:
svm = linear_model.SGDClassifier(loss='modified_huber').fit(features,y_train)

In [60]:
y_pred = svm.predict(test_features)
y_probas = svm.predict_proba(test_features)

print(confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred, target_names=list(le.classes_)))

[[204   2   0   0   1]
 [  1 394   1   2   6]
 [  1   0  82   1   5]
 [  0   6   0 331   2]
 [  0   1   0   1 209]]
                  precision    recall  f1-score   support

          Comedy       0.99      0.99      0.99       207
   Entertainment       0.98      0.98      0.98       404
Film & Animation       0.99      0.92      0.95        89
           Music       0.99      0.98      0.98       339
  People & Blogs       0.94      0.99      0.96       211

        accuracy                           0.98      1250
       macro avg       0.98      0.97      0.97      1250
    weighted avg       0.98      0.98      0.98      1250



# Random Forest

In [61]:
rf = RandomForestClassifier(n_estimators=100).fit(features,y_train)

In [62]:
y_pred = rf.predict(test_features)
y_probas = rf.predict_proba(test_features)

print(confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred, target_names=list(le.classes_)))

[[205   0   0   0   2]
 [  3 396   0   2   3]
 [  0   1  81   1   6]
 [  0   3   0 335   1]
 [  0   0   0   4 207]]
                  precision    recall  f1-score   support

          Comedy       0.99      0.99      0.99       207
   Entertainment       0.99      0.98      0.99       404
Film & Animation       1.00      0.91      0.95        89
           Music       0.98      0.99      0.98       339
  People & Blogs       0.95      0.98      0.96       211

        accuracy                           0.98      1250
       macro avg       0.98      0.97      0.97      1250
    weighted avg       0.98      0.98      0.98      1250

